export const SET_COLOR_THEME = 'SET_COLOR_THEME';
export const SET_SELECTED_PAGE = 'SET_SELECTED_PAGE';
export const SET_IS_OVERLAY_SHOWN = 'SET_IS_OVERLAY_SHOWN';
export const SET_METRICS = 'SET_METRICS';